CREATE TABLE Characters (
  ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(40) NOT NULL,
  Alter_ego VARCHAR(40) NOT NULL,
  Location VARCHAR(40) NOT NULL,
  Occupation VARCHAR(40) NOT NULL,
  Side VARCHAR (40) NOT NULL,
  Universe VARCHAR (40) NOT NULL,
  PRIMARY KEY (ID)
);
